accountapp/urls.py

from django.urls import path
from . import views

app_name = 'accountapp'
urlpatterns = [
    
    path('', views.myaccount, name='myaccount'),
    path('register/', views.register, name='register'),

]

blog/urls.py

from django.urls import path
from .import views

app_name ="blog"

urlpatterns = [
    
    path('',views.blog,name='blog'),
    path('blog/<slug:slug>/',views.blogdetail,name='detail'),
]

contactapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include('myapp.urls')),
    path('',include('blog.urls',namespace='blog')),
    path('course/',include('courseapp.urls')),
    path('importapp/',include('importapp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('register/',include('accountapp.urls'))
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

courseapp/urls.py

from django.urls import path
from . import views
app_name='courseapp'
urlpatterns = [
    path('',views.course,name='course'),
 
]

importapp/urls.py

from django.urls import path
from . import views


urlpatterns = [
    path('',views.student, name='student'),
  
]

myapp/urls.py

from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

#put your app differntiate from the other app
app_name = 'myapp'

urlpatterns = [
    path('',views.index,name='index'),
    
] 

accountapp/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
#Importing your Richtext file here
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Blog (models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField()
    content = RichTextField() # Note this RichTextField model provided by Ckeditor
    tag = models.CharField(max_length=100)
    Slug = models.SlugField(max_length=200, unique=True)
    date = models.DateTimeField(auto_now_add=True)

#This method used name the Blog object name 
    def __str__(self):
        return self.title
        
#This is used to determine the order of the blog a/c to Date
    class Meta:
        ordering = ('-date',)
    

importapp/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=50)
    section = models.CharField(max_length=10)
    rollno = models.IntegerField(default=1) #Note here the Primat key make this fi
    phone = models.IntegerField()
    topic = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    

accountapp/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect

    # import the form for user creation
from django.contrib.auth.forms import UserCreationForm

# for checking of authentication we should import authenticate and login for login

from django.contrib.auth import authenticate, login

# Create your views here.
def myaccount(request):
    return render(request, 'accountapp/account.html')

def register(request):
    if request.method == 'POST':
        
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form .cleaned_data['username']
            password = form.cleaned_data['password1']

            user = authenticate(username = username, password = password)
            #Check for login status with your database data.
            login(request, user)
            return redirect('myaccount')
            
    else:
        form = UserCreationForm()

    context = {'form' : form}

    return render(request, 'registration/register.html', context)

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog

# Create your views here.
def blog(request):
    blogs = Blog.objects.all()
    return render(request, 'blog/blogindex.html', {'blogs': blogs})


def blogdetail(request, slug):
    post = get_object_or_404(Blog, Slug = slug)
    return render(request,'blog/blogdetail.html', {'blog':post})

courseapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def course(request):
    return render(request, 'courseapp/course.html')

importapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def student(request):
    return HttpResponse("Student detail here..")

myapp/views.py
from django.shortcuts import render,redirect
from .import form
from .form import ContactForm
from django.core.mail import EmailMessage
from django.template.loader import get_template

# Create your views here.

def index(request):

    Contact_Form = ContactForm
    if request.method == "POST":
        form = Contact_Form(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get('contact_name')
            contact_email = request.POST.get('contact.email')
            contact_content = request.POST.get('content')

            template = get_template('myapp/contact_form.txt')

            context = {
                'content_name' : contact_name,
                'content_email' : contact_email,
                'contact_content': contact_content,
            }
            content = template.render(context)

            email = EmailMessage(
                'New Contact form email',
                content,
                "myBlogger" + '',
                ['sudhanshuraj8917@gmail.com'],
                headers={'Reply to':
                 contact_email }

            )
            email.send()

            return redirect('myapp:index')

    return render(request,'myapp/index.html',{'form':Contact_Form})

accountapp/templates/accountapp/account.html
<body>
<h1>This is the index page!!</h1>
{% if user.is_authenticated %}
<h2>Your name is : {{ user.username }}</h2>
{% else %}
<h2>You are not logged in</h2>
{% endif %}
</body>

blog/templates/blog/blogdetail.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
      <!--Import materialize.css-->
      <link rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  </head>
  <body>
    <div class="container card mb-3 text-center">
  <img class="card-img-top" src="{{ blog.image.url }}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{ blog.title }}</h5>
    
    <div class="row">
        <div class="col s12 m6">
        <div class="card blue-grey darken-1">
            <div class="card-content white-text">
            <span class="card-title">{{ blog.title }}</span>
            <p>{{ blog.content |safe}}</p> <!-- We should pipline |safe if we are using the ckeditor properties-->
            </div>
            <div class="card-action">
            <h6>{{ blog.date |time}}</h6>
            </div>
        </div>
        </div>
    </div>
    <p class="card-text"><small class="text-center">{{ blog.date |time}}</small></p>
  </div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/blogindex.html

{% extends "myapp/base.html" %}
{% load static %}


 {% block content %}

 {% for blog in blogs %}

<br />
<!-- Note:  slug=blog.Slug here -->
<a href="{% url 'blog:detail' slug=blog.Slug %}">

    <div class="row">
      <div class="col s12 m6">
        <div class="card card-panel hoverable">
          <div class="card-image">
            <img src="{{ blog.image.url }}">
            <span class="card-title teal darken-4 text-black">{{ blog.title }}</span>
            <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">thumb_up
  </i></a>
          </div>
          <div class="card-content">
            <p>{{ blog.content|truncatechars:200 |safe}}<a href="{% url 'blog:detail' slug=blog.Slug %}">Read more</a></p>
          </div>

            <div class="card-action center-align">
            <p>{{ blog.tag }}  &nbsp&nbsp&nbsp&nbsp;
              {{blog.date | date }}</p>
          </div>
        

        </div>
      </div>
    </div>

</a>
            
 {% endfor %}
{% endblock content %}

courseapp/templates/courseapp/course.html
{% load static %}
<!-- Video Pop when plays -->
<!DOCTYPE html>
<html>
<head>
	<title>Video Pop-up - Easy Tutorials </title>
	<link rel="stylesheet" type="text/css" href="{% static 'courseapp/style.css' %}">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

			<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>

<div class="container text-center">
		<h1>OnClick Video PopUp</h1>
		
		<div class="row">
			<div class="col-md-4">
				<img src="{% static 'image/Django.png' %}" class="img-fluid">
				<img src="{% static 'image/icon.png' %}" class="play-btn" data-toggle="modal" data-target="#play-video-1">
			</div>

			<div class="col-md-4">
				<img src="{% static 'image/sath.png' %}" class="img-fluid">
				<img src="{% static 'image/icon.png' %}" class="play-btn" data-toggle="modal" data-target="#play-video-2">
			</div>

			<div class="col-md-4">
				<img src="{% static 'image/song1.png' %}" class="img-fluid">
				<img src="{% static 'image/icon.png' %}" class="play-btn" data-toggle="modal" data-target="#play-video-3">
			</div>

		</div>

		<!-- another row -->

	<!-- 	<div class="row">
			<div class="col-md-4">
				<img src="sath.png" class="img-fluid">

				<img src="icon.png" class="play-btn" data-toggle="modal" data-target="#">
			</div>

		</div>
 -->
</div>


<!-- Modal -->
<div class="modal fade" id="play-video-1">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
       
      <div class="modal-body">
        <video width="100%" controls autoplay loop>
        	<source src="{% static 'video/Django2.mp4' %}" type="video/mp4">
        </video>
      </div>
      
    </div>
  </div>
</div>


<div class="modal fade" id="play-video-2">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
       
      <div class="modal-body">
        <video width="100%" controls autoplay loop>
        	<source src="{% static 'video/teri.mp4' %}" type="video/mp4">
        </video>
      </div>
      
    </div>
  </div>
</div>

<div class="modal fade" id="play-video-3">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
       
      <div class="modal-body">
        <video width="100%" controls autoplay loop>
        	<source src="{% static 'video/tumhiana.mp4' %}" type="video/mp4">
        </video>
      </div>
      
    </div>
  </div>
</div>

</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
      <!--Import materialize.css-->
      <link rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
    <nav>
      <div class="container">
        <div class="nav-wrapper">

          <a href="" class="brand-logo">Logo</a>
          
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="">Home</a></li>
            <li><a href="">Course</a></li>
            <li><a href="">Blog</a></li>
            <li><a href="">Contact</a></li>
          <!--  {% if user.is_authenticated %}
            <li><a href="">Log Out</a></li>
            <li><a href="">Change Password</a></li>
            {% else %}
            <li><a href="">Sign Up</a></li>
            <li><a href="">Log In</a></li>
            {% endif %} -->

          </ul> 
        </div>
      </div>
    </nav>


        {% block content %}

        {% endblock %}

      <!--JavaScript at end of body for optimized loading-->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="{% static 'materialize/js/materialize.min.js' %}"></script>
    </body>
  </html>
        

myapp/templates/myapp/index.html
{% load static %}
 <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
      <!--Import materialize.css-->
      <link rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"/>


      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

</head>


    <div class="container">
        <div  class="row">
            <div  class="col l12">
                <h1 class="card-panel  pink lighten-5 center-align">Contact form</h1>
                <div class="card-panel  pink lighten-5 mx-4">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                    <button class="btn waves-effect waves-light" type="submit">Send Email</button>
                    </form>
                </div>
            </div>
        </div>
    </div>